/// Flutter icons MovieAppIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MovieAppIcon
///      fonts:
///       - asset: fonts/MovieAppIcon.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
///
import 'package:flutter/widgets.dart';

class MovieAppIcon {
  MovieAppIcon._();

  static const _kFontFam = 'MovieAppIcon';
  static const String? _kFontPkg = null;

  static const IconData heart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartEmpty = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
